### ISSUE TITLE
Limit the Pens

### ISSUE THREAD

**Issue by grayghostvisuals** [TimPietrusky/pentizr#1]
Feature Request : 
1. Ability to limit the pens shown please :)

**Comment by TimPietrusky** [comment]
Can you please verify that this works for you?

**Comment by grayghostvisuals** [comment]
Oh dude! that's sweet! Verified and Checked in FF 16.0.2, Safari 6.0.1, Chrome 22.0.1229.94 and Opera 12.02 on Mac Lion 10.8.2.

**Comment by TimPietrusky** [comment]
Thanks for testing this dude!
