### ISSUE TITLE
iframe support dropped?

### ISSUE THREAD

**Issue by KevinGimbel** [TimPietrusky/pentizr#4]
Seems that CodePen no longer supports the use of full source links with `iframe`. 

Therefore the use of `<iframe src={{urlFull}}></iframe>` is not working. 
Also tried to load it "manually" by putting the URL in an iframe without pentizr - same result, nothing shows up. 

Anyone knows another way to get this to work?

**Comment by TimPietrusky** [comment]
CodePen [fixed this iframe issue](https://twitter.com/CodePen/status/333292920444686336):

> @CodePen @_kevinatari @TimPietrusky It should be back. I was denying the embed with the X-Frame-Options. Check it out.
